name: first_action
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo "Hello world"
      - name: say bye
        run: echo "goodbye world"




